version: "3.7"

services:

  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"

  dbauth:
    image: evidence-dbauth
    container_name: evidence_dbauth
    build:
      context: database/dbauth/
    volumes:
      - ./database/dbauth/demo/test-user.sql:/docker-entrypoint-initdb.d/test-user.sql
    ports:
       - "5432:5432"
    # network_mode: "host"  # host mode OR port mapping
    restart: unless-stopped
    environment:
      - "POSTGRES_USER=evidence"
      - "POSTGRES_PASSWORD=evidence"

  dbeval: 
    image: cassandra:4.0
    container_name: evidence_dbeval
    ports:
       - "9042:9042"
    # network_mode: "host"  # host mode doesn't work
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10
    cap_add:
      - SYS_NICE
    # environment:
      # see https://hub.docker.com/r/bitnami/cassandra/

  api:
    image: evidence-api
    container_name: evidence_api
    build:
      context: restapi/
    ports:
      - "7070:80"
    # network_mode: "host"  # host mode OR port mapping
    depends_on:
      - dbauth
      - dbeval
    restart: unless-stopped  # very important because CQL takes 3-5 min. to start
    environment:
      - "DBEVAL_NODES=dbeval"
      - "DBAUTH_HOST=dbauth" 
      - "ACCESS_SECRET_KEY=acceba8d51a6ee8423447b41ad85d696ca221d01fd1e4031bae6a9118a0f43b6"
      # Mailer Settings
      - "SMTP_SERVER=mail"
      - "SMTP_PORT=1025"
      # - "SMTP_TLS="
      # - "SMTP_USER="
      # - "SMTP_PASSWORD="
      - "FROM_EMAIL=test@evidence-demo.org"
      # - "VERIFY_PUBLIC_URL=http://mydomain:8080"
      # Fastapi/gunicorn settings, see https://github.com/tiangolo/uvicorn-gunicorn-docker/tree/master#workers_per_core
      - "WORKERS_PER_CORE=0.5"

  app:
    image: evidence-app
    container_name: evidence_app
    build:
      context: webapp/
    volumes:
      - ./docker-compose-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9090:9090"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  dbauth:
  dbeval:

# networks:
#   default:
#     driver: bridge
