version: "3.7"
services:
  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
  db:
    image: evidence-db
    build:
      context: database/
    ports:
       - "5432:5432"
    environment:
      - "POSTGRES_USER=evidence"
      - "POSTGRES_PASSWORD=evidence"
    volumes:
      - ./database/dbauth/demo/test-user-for-app-demo.sql:/docker-entrypoint-initdb.d/2001-test-user-for-app-demo.sql
      - ./database/dbappl/demo/toy-data-for-app-demo.sql:/docker-entrypoint-initdb.d/2002-toy-data-for-app-demo.sql
      - db:/var/lib/postgresql/data
  api:
    image: evidence-api
    build:
      context: restapi/
    environment:
      - "DBAPPL_HOST=db"
      - "DBAUTH_HOST=db"
      - "ACCESS_SECRET_KEY=acceba8d51a6ee8423447b41ad85d696ca221d01fd1e4031bae6a9118a0f43b6"
      # Mailer Settings
      - "SMTP_SERVER=mail"
      - "SMTP_PORT=1025"
      # - "SMTP_TLS="
      # - "SMTP_USER="
      # - "SMTP_PASSWORD="
      # - "FROM_EMAIL="
      # - "VERIFY_PUBLIC_URL=http://mydomain:8080"
      # Fastapi/gunicorn settings, see https://github.com/tiangolo/uvicorn-gunicorn-docker/tree/master#workers_per_core
      - "WORKERS_PER_CORE=0.5"
      # - "MAX_WORKERS=2"
    ports:
      - "8080:80"

  simiscore-biblio:
    image: evidence-simiscore-biblio
    build:
      context: simiscore-biblio/
      dockerfile: Dockerfile
    environment:
      - "WORKERS_PER_CORE=0.5"
      # - "MAX_WORKERS=2"
    ports:
      - "8081:80"

  simiscore-kshingle:
    image: evidence-simiscore-kshingle
    build:
      context: simiscore-kshingle/
      dockerfile: Dockerfile
    environment:
      - "WORKERS_PER_CORE=0.5"
      # - "MAX_WORKERS=2"
    ports:
      - "8082:80"

  simiscore-semantic:
    image: evidence-simiscore-semantic
    build:
      context: simiscore-semantic/
      dockerfile: Dockerfile
    environment:
      - "WORKERS_PER_CORE=0.5"
      # - "MAX_WORKERS=2"
    ports:
      - "8083:80"

  simiscore-syntax:
    image: evidence-simiscore-syntax
    build:
      context: simiscore-syntax/
      dockerfile: Dockerfile
    environment:
      - "WORKERS_PER_CORE=0.5"
      # - "MAX_WORKERS=2"
    ports:
      - "8084:80"

  app:
    image: evidence-app
    build:
      context: webapp/
    volumes:
      - ./docker-compose-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9090:9090"

volumes:
  db:
