version: "3.7"

services:

  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"

  dbauth:
    image: evidence-dbauth
    container_name: evidence_dbauth
    build:
      context: database/dbauth/
    ports:
       - "5432:5432"
    environment:
      - "POSTGRES_USER=evidence"
      - "POSTGRES_PASSWORD=evidence"
    volumes:
      - ./database/dbauth/demo/test-user.sql:/docker-entrypoint-initdb.d/test-user.sql

  dbeval: 
    container_name: evidence_dbeval
    image: cassandra:4.0
    # image: evidence-dbeval
    # build:
    #   context: database/dbeval/
    ports:
       - "9042:9042"
    restart: always
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 10
    cap_add:
      - SYS_NICE

  dbeval-install:
      container_name: evidence_dbeval_install
      image: cassandra:4.0
      depends_on:
        dbeval:
          condition: service_healthy
      volumes:
        - ./database/dbeval/setup/000-install.cql:/000-install.cql
        - ./database/dbeval/demo/999-toy-data1.cql:/999-toy-data1.cql
      command: /bin/bash -c "cqlsh dbeval -f /000-install.cql && cqlsh dbeval -f /999-toy-data1.cql"
      restart: "no"

  api:
    image: evidence-api
    container_name: evidence_api
    build:
      context: restapi/
    environment:
      - "DBAPPL_HOST=dbauth"
      - "DBAUTH_HOST=dbauth"
      - "ACCESS_SECRET_KEY=acceba8d51a6ee8423447b41ad85d696ca221d01fd1e4031bae6a9118a0f43b6"
      # Mailer Settings
      - "SMTP_SERVER=mail"
      - "SMTP_PORT=1025"
      # - "SMTP_TLS="
      # - "SMTP_USER="
      # - "SMTP_PASSWORD="
      # - "FROM_EMAIL="
      # - "VERIFY_PUBLIC_URL=http://mydomain:8080"
      # Fastapi/gunicorn settings, see https://github.com/tiangolo/uvicorn-gunicorn-docker/tree/master#workers_per_core
      - "WORKERS_PER_CORE=0.5"
      # - "MAX_WORKERS=2"
    ports:
      - "8080:80"
    depends_on:
      - "dbauth"
      - "dbeval"

  app:
    image: evidence-app
    container_name: evidence_app
    build:
      context: webapp/
    volumes:
      - ./docker-compose-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9090:9090"
    depends_on:
      - "api"

volumes:
  dbauth:
  dbeval:
