#!/usr/bin/env python3

import os
from pathlib import Path
from subprocess import check_call, check_output

check_call(['docker-compose', 'build'])

minor_version = check_output(
    ["git", "rev-list", "HEAD", "--count"], encoding='utf8'
)

version = (Path(__file__) / '..' / 'VERSION').resolve().read_text().strip()
version = os.environ.get('VERSION', version)
version = f'{version}.{minor_version.strip()}'

for service in ['dbauth', 'api', 'app']:
    image_tag = f'evidence-{service}:latest'
    release_tag = f'docker-registry.zdl.org/zdl-evidence/{service}:{version}'
    check_call(['docker', 'tag', image_tag, release_tag])
    check_call(['docker', 'push', release_tag])
